In [17]:
import pandas as pd
import numpy as np

In [18]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [19]:
df=pd.read_csv('covid_toy.csv')

In [20]:

df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.20,random_state=42)

In [22]:
x_train.head()

    age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [23]:
from sklearn.compose import ColumnTransformer

In [49]:
transform=ColumnTransformer(transformers=[
    ('tran1',SimpleImputer(),['fever']),
    ('tran2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tran3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [50]:
x_train_transform=transform.fit_transform(x_train)

In [51]:
X_test_transform=transform.fit_transform(x_test).shape

In [52]:
x_train_transform=pd.DataFrame(x_train_transform,columns=x_train.columns)
X_test_transform=pd.DataFrame(X_test_transform,columns=x_test.columns)

ValueError: Shape of passed values is (80, 7), indices imply (80, 5)