In [ ]:
import pandas as pd
import numpy as np

In [18]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [19]:
df=pd.read_csv('covid_toy.csv')

In [ ]:

df.head()

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.20,random_state=42)
# here we are spliting the traning and testing data in two parts

In [ ]:
x_train.head(10)

    age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [ ]:

from sklearn.compose import ColumnTransformer
# here we are calling the columntransformar class from sklearn

In [ ]:
transform=ColumnTransformer(transformers=[
    ('tran1',SimpleImputer(),[' fever ']),
    # here if we need to pass transformar we need to passs them through an tupplr like tran1,tran2,tran3
    # next inside the tupple we have to pass the transformar object like SimpleImputyer
    # next we have to pass the column names where we want to use this transformar and the column names should be pass through in a  list
    # like ['fever]

    ('tran2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    # we have to use three diffrent tranfromar so we are passing three tupple
    # next inside the tupple we have to pass the transformar object like ordinaEncoding
    # after that we have to pass the catagories inside the ordinalEncoder,like[['mild','stong']]
     # next we have to pass the column names where we want to use this transformar and the column names should be pass through in a  list

    ('tran3',OneHotEncoder(sparse_output= False,drop='first'),['gender','city'])
    # same as simple imputer
    #sparse_output =False is use so that we dont get sparse array ,drop='first' is mainly used to handle multicollinearity

],remainder='passthrough')#reminder=passthrough mean the column we are not transforming those are pass through without any changes

In [65]:
x_train_transform=transform.fit_transform(x_train)
X_test_transform=transform.fit_transform(x_test)
# here we fit the trainning and testing data