In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [5]:
df = pd.read_csv('titanic_updated.csv')
# here we create missing values in the dataset just to practice so this is not the real dataset

In [4]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [12]:
df.isnull().mean()
# we can see we have missing values at Age and Fare

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [16]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('Survived',axis=1),df['Survived'],test_size=0.20,random_state=2)

In [17]:
x_train.head()

      Age     Fare  Family
30   40.0  27.7208       0
10    4.0  16.7000       2
873  47.0   9.0000       0
182   9.0  31.3875       6
876  20.0   9.8458       0

In [18]:
y_train.head()

30     0
10     1
873    0
182    0
876    0
Name: Survived, dtype: int64

In [ ]:
# Now we will gonna do mean and median imputation so we need the mean,median of Age and Fare
mediam_age=x_train['Age'].median()
mean_age=x_train['Age'].mean()

mediam_fare=x_train['Fare'].median()
mean_fare=x_train["Fare"]