### We lode the pandas and the n we lode the datset

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("House.csv")

In [3]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,313000.0,3,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2384000.0,5,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,342000.0,3,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,420000.0,3,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,550000.0,4,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [4]:
x=df.drop('price',axis=1)
y=df['price']
# Here in x we will drop the output column which is price and other then that column
# we will store the other column which are the input column in x
# when we again call the datafream 
# Then we will pass the price column in y variable because we are not droping the price permantly in x
# so we seperated our input and output column in x and y simultaneously

In [5]:
from sklearn.model_selection import train_test_split
# Her we are calling a class from sklearn name model_selection where we have a function called tarin_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.20,random_state=42)

# Here we calling the train_test_split function and we are storing the split result in x_train,x_test,Y_train,y_test
# the function automatically split the data

In [7]:
x_test.head(5)

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
3683,3,2.50,1460,1613,2.0,0,0,3,1180,280,2007,0,6710 Alonzo Ave NW,Seattle,WA 98117,USA
4411,5,2.25,2000,7900,1.0,0,0,4,1300,700,1986,0,3202 S 194th St,SeaTac,WA 98188,USA
2584,3,3.25,2940,5432,3.0,0,3,4,2440,500,1978,2000,150 Highland Dr,Seattle,WA 98109,USA
69,3,2.50,2200,7350,1.0,0,0,5,1570,630,1988,0,13420 SE 182nd St,Renton,WA 98058,USA
1844,3,2.50,1720,8755,1.0,0,0,3,1000,720,1983,2009,31607 45th Pl SW,Federal Way,WA 98023,USA

In [8]:
x_test.head(5)

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
3683,3,2.50,1460,1613,2.0,0,0,3,1180,280,2007,0,6710 Alonzo Ave NW,Seattle,WA 98117,USA
4411,5,2.25,2000,7900,1.0,0,0,4,1300,700,1986,0,3202 S 194th St,SeaTac,WA 98188,USA
2584,3,3.25,2940,5432,3.0,0,3,4,2440,500,1978,2000,150 Highland Dr,Seattle,WA 98109,USA
69,3,2.50,2200,7350,1.0,0,0,5,1570,630,1988,0,13420 SE 182nd St,Renton,WA 98058,USA
1844,3,2.50,1720,8755,1.0,0,0,3,1000,720,1983,2009,31607 45th Pl SW,Federal Way,WA 98023,USA

In [9]:
y_train.head(5)

1828    400000.0
1573    400000.0
319     258000.0
653     565000.0
2137    550000.0
Name: price, dtype: float64

In [10]:
y_test.head(5)

3683     544000.0
4411          0.0
2584    1712500.0
69       365000.0
1844     275000.0
Name: price, dtype: float64